[package]
name = "l0"
version = "0.1.0"
edition = "2021"
description = "A small typed, zero-indexed Lua-like stack VM"

[lib]
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "l0"
path = "src/main.rs"

[[example]]
name = "rust_host"
path = "examples/host_functions/rust_host.rs"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
half = "=2.3.1"
md-5 = "0.10.6"
ndarray = "0.15.6"
ndarray-linalg = { version = "0.16.0", features = ["openblas-system"] }
openblas-src = { version = "0.10", features = ["system", "rustls"] }
#candle-core = { version = "0.6", features = ["cuda"] }
candle-core = { version = "0.6"}
candle-nn = { version = "0.6" }
safetensors = "0.4.3"
tokenizers = "0.15"

[[example]]
name = "md5_host"
path = "examples/host_functions/md5_host.rs"
[[example]]
name = "exec_host"
path = "examples/host_functions/exec_host.rs"
