[package]
name = "l0"
version = "0.1.0"
edition = "2021"
description = "A small typed, zero-indexed Lua-like stack VM"

[lib]
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "l0"
path = "src/main.rs"

[[example]]
name = "rust_host"
path = "examples/host_functions/rust_host.rs"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
cc = "1.0"
half = "2.7.1"
md-5 = "0.10.6"
# Новые зависимости для линейной алгебры и работы с тензорами
ndarray = "0.15.6"
ndarray-linalg = { version = "0.16.0", features = ["openblas-system"] }
openblas-src = { version = "0.10", features = ["system", "rustls"] }
#cudarc = { version = "0.11", features = ["nvrtc", "driver", "cuda-version-from-build-system", "cusolver"] }
cudarc = { version = "0.11", features = ["nvrtc", "driver", "cuda-version-from-build-system"] }
# === НОВЫЕ ЗАВИСИМОСТИ CANDLE ===
candle-core = { version = "0.6.0", features = ["cuda"] }
# Модуль нейросетей (Linear, Conv2d, LayerNorm, Softmax и т.д.)
candle-nn = { version = "0.6.0", features = ["cuda"] }
# Модуль для парсинга Hugging Face моделей (.safetensors)
safetensors = "0.4.3"

[[example]]
name = "md5_host"
path = "examples/host_functions/md5_host.rs"
[[example]]
name = "exec_host"
path = "examples/host_functions/exec_host.rs"
