[package]
name = "l0"
version = "0.1.0"
edition = "2021"
description = "A small typed, zero-indexed Lua-like stack VM"

[lib]
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "l0"
path = "src/main.rs"

[[example]]
name = "rust_host"
path = "examples/host_functions/rust_host.rs"

[profile.release]
lto = true
codegen-units = 1
